config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-4 banner">
  <%= link_to "Simple Airbnb", flats_path%>
  <%= link_to "Add Flat", new_flat_path%>
</div>
<div class="container">
<h1>All our Flats (<%= @flats.count %>)</h1>
  <div class="row mt-3">
  <%@flats.each do |flat|%>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
        <div class="back-color card-body">
          <img src="" alt="A flat">
          <h2><%= flat.name%></h2>
          <%= flat.address%>
          <div class="d-flex align-items-center">
            <%= flat.price_per_night %>
            <i class="fa-solid fa-euro-sign me-3"></i>

            <%= flat.number_of_guests%>
            <i class="fa-solid fa-users"></i>
          </div>
        </div>
        <div class="card-body">
          <%= link_to "More Info", flat_path(flat.id) %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/flats/show.html.erb
<div class="d-flex justify-content-between align-items-center mb-4 banner">
  <%= link_to "Simple Airbnb", flats_path%>
  <%= link_to "Add Flat", new_flat_path%>
</div>
<div class="map">
</div>
<div class="container d-flex justify-content-center">
  <div class="container-flat flex-column">
    <div class="card grey" style="width: 18rem;">
      <div class="card-body">
      <h1><%= @flat.name %></h1>
      <p> <%= @flat.address %> </p>
      </div>
    </div>
    <div class="card grey" style="width: 18rem;">
      <div class="card-body">
        <h3>Details</h3>
        <p> <%= @flat.price_per_night%> </p>
        <p> <%= @flat.number_of_guests%> </p>
      </div>
    </div>
  </div>
  <div class="container-info flex-column">
    <div class="card grey">
      <div class="card-body">
        <div class="social-media">
          <h4>Share</h4>
          <%# fontawsome %>
        </div>
      </div>
    </div>
    <div class="card grey" style="width: 18rem;">
      <div class="card-body">
        <div class="form-control">
          <h3>Book this place!</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>